# =============================
# ğŸŒ± H2 ë°ì´í„°ë² ì´ìŠ¤ ì„¤ì •
# =============================
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:nemodb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  # =============================
  # âœ‰ï¸ ë©”ì¼(SMTP) ì„¤ì •
  # =============================
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # =============================
  # ğŸ“¸ íŒŒì¼ ì—…ë¡œë“œ / S3 ì„¤ì •
  # =============================
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
  profiles:
    active: local

# =============================
# â˜ï¸ S3 ë²„í‚· ê´€ë ¨ ì„¤ì •
# =============================
app:
  s3:
    bucket: nemo-dev-photos
    region: ap-northeast-2
    endpoint:
    accessKey: test
    secretKey: test
    pathStyle: true

# =============================
# ğŸŒ ê¸°ë³¸ í”„ë¡œí•„
# =============================
