app:
  public-base-url: http://10.0.2.2:8080

  s3:
    bucket: nemo-dev-photos
    region: ap-northeast-2
    endpoint: http://localhost:4566
    accessKey: test
    secretKey: test
    pathStyle: true
